---
development:
  cloud_name: adoundakov
  api_key: '897577337498324'
  api_secret: JH5A8BOlbOzi05zVmjiZCbj2ibM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: adoundakov
  api_key: '897577337498324'
  api_secret: JH5A8BOlbOzi05zVmjiZCbj2ibM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: adoundakov
  api_key: '897577337498324'
  api_secret: JH5A8BOlbOzi05zVmjiZCbj2ibM
  enhance_image_tag: true
  static_image_support: false
